version: "3"

services:

  movie-api:
    image: node:12.6.0 
    container_name: movie-ui-docker
    volumes:
      - ./:/home/app
    environment:
      BACK_HOST: 'host.docker.internal'
      BACK_PORT: 8080
      PORT: 3030
    working_dir: /home/app
    command: bash -c "node server.js"
    ports:
      - 3030:3030
