pipeline {
    agent {
        docker {
            image 'node:12.6.0' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
            post {
                success {
                    sh 'tar -cvf dist.tar dist/'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'dist.tar', fingerprint: true
        }
    }
}