pipeline {
    agent {
        docker {
            image 'node:12.6.0' 
        }
    }
    stages {
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build') {
            steps {
                sh 'npm,m run build'
            }
            post {
                success {
                    sh 'tar -cvf dist.tar dist/ package.json package-lock.json'
                    archiveArtifacts artifacts: 'dist.tar', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            sh 'tar -cvf test-results.tar mochawesome-report/'
            archiveArtifacts artifacts: 'test-results.tar', fingerprint: true
        }

        failure {
            mail to: 'jmendozaa@psl.com.co', 
            subject: 'Failed Pipeline: ${currentBuild.fullDisplayName}',
            body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}